# Generated by Django 5.2.6 on 2025-09-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
