# Generated by Django 5.2.6 on 2025-10-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
