# Generated by Django 5.2.6 on 2025-10-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('no_of_people', models.IntegerField()),
                ('preferred_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
